# Generated by Django 5.1.5 on 2025-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course_name', models.CharField(max_length=150)),
                ('course_rating', models.IntegerField()),
                ('content_understandability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('content_relevance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('content_suggestions', models.TextField(blank=True)),
                ('interface_rating', models.IntegerField()),
                ('technical_issues', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('issue_details', models.TextField(blank=True)),
                ('navigation_easy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('usability_suggestions', models.TextField(blank=True)),
                ('recommend', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('best_feature', models.TextField(blank=True)),
                ('additional_feedback', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
