# Generated by Django 5.1.5 on 2025-03-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_feedback_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='submission_date',
        ),
    ]
